#!/usr/bin/env python3
"""Compose docs/social-preview.png from docs/bg-raw.png (generated by media-tools).

Layout: 1280x640 cover-crop of the background + left-to-right dark gradient
overlay + title / subtitle text + pill tags. Run from the repo root:

    python3 scripts/make-banner.py
"""
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
W, H = 1280, 640
FONT_BOLD = "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
FONT_REG = "/System/Library/Fonts/Supplemental/Arial.ttf"
FONT_CJK = "/System/Library/Fonts/Supplemental/Arial Unicode.ttf"
ACCENT = (77, 107, 254)  # DSH blue #4D6BFE

TITLE = "dsh-skill-router"
SUB_EN = "Rule-first skill routing: pours matched skills, stays silent when unsure"
SUB_ZH = "任务命中才倒酒，拿不准就闭嘴 —— DSH 技能路由执行器"
TAGS = ["Pre-step hook", "Rule-first matching", "Zero token cost", "Works with skill-bartender"]


def cover_crop(img: Image.Image, w: int, h: int) -> Image.Image:
    scale = max(w / img.width, h / img.height)
    img = img.resize((round(img.width * scale), round(img.height * scale)))
    left = (img.width - w) // 2
    top = (img.height - h) // 2
    return img.crop((left, top, left + w, top + h))


def main() -> None:
    bg = Image.open(ROOT / "docs/bg-raw.png").convert("RGBA")
    canvas = cover_crop(bg, W, H)

    # Left-to-right dark gradient so text stays legible.
    alpha = Image.linear_gradient("L").resize((W, H)).point(
        lambda v: 235 - int((235 - 40) * v / 255)
    )
    overlay = Image.new("RGBA", (W, H), (10, 16, 44, 255))
    overlay.putalpha(alpha)
    canvas = Image.alpha_composite(canvas, overlay)

    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(FONT_BOLD, 56)
    en_font = ImageFont.truetype(FONT_REG, 27)
    cjk_font = ImageFont.truetype(FONT_CJK, 23)
    tag_font = ImageFont.truetype(FONT_CJK, 17)

    x = 60
    # Accent bar + title
    draw.rectangle((x, 208, x + 8, 272), fill=ACCENT)
    draw.text((x + 26, 198), TITLE, font=title_font, fill=(255, 255, 255))
    draw.text((x + 26, 272), SUB_EN, font=en_font, fill=(215, 224, 255))
    draw.text((x + 26, 314), SUB_ZH, font=cjk_font, fill=(159, 176, 224))

    # Pill tags
    tx, ty = x + 26, 384
    for label in TAGS:
        w = draw.textlength(label, font=tag_font) + 36
        draw.rounded_rectangle((tx, ty, tx + w, ty + 36), radius=18, outline=ACCENT, width=2)
        draw.text((tx + 18, ty + 9), label, font=tag_font, fill=(255, 255, 255))
        tx += w + 12

    out = ROOT / "docs" / "social-preview.png"
    canvas.convert("RGB").save(out)
    print("wrote:", out, f"({W}x{H})")


if __name__ == "__main__":
    main()
